export interface WorldTheme { name: string; eyebrow: string; description: string; accent: string; ground: string; base: string; tile: string; sky: string; }
export const WORLD_THEMES: Record<string, WorldTheme> = {
  abyss: { name: 'The Sunken Observatory', eyebrow: 'TWENTY THOUSAND LEAGUES OF POSSIBILITY', description: 'A pearl-domed observatory, coral gardens, and a golden submarine on the ocean floor.', accent: '#80d8d0', ground: '#438b99', base: '#214657', tile: '#ceeae5', sky: '#102d43' },
  lunar: { name: 'Moonbase Commons', eyebrow: 'A SMALL STEP FOR THE COMMON GOOD', description: 'Habitat domes, solar arrays, a lunar rocket, and a ringed planet above the outpost.', accent: '#b8c6f2', ground: '#858ba8', base: '#363e61', tile: '#e1e6f4', sky: '#131b35' },
  mycelium: { name: 'Mushroom Hollow', eyebrow: 'BIG DREAMS UNDER LITTLE CAPS', description: 'Giant spotted mushrooms, a fairy-ring pond, and a lantern-lit woodland village.', accent: '#e4ba86', ground: '#81966c', base: '#4c5b3c', tile: '#f0e4c8', sky: '#22372c' },
  oasis: { name: 'The Saffron Caravan', eyebrow: 'WHERE THE DUNES MEET THE WATER', description: 'Stepped pyramids, a turquoise oasis, palm groves, and a sunlit market.', accent: '#edc47a', ground: '#d5b67b', base: '#946847', tile: '#f6e6c3', sky: '#45332d' },
  confection: { name: 'Sugarplum Borough', eyebrow: 'PROPERTY WITH A CHERRY ON TOP', description: 'A frosted layer cake, candy-cane arches, lollipop trees, and gumdrop gardens.', accent: '#f0abc8', ground: '#d9b5c8', base: '#93617e', tile: '#fff0de', sky: '#402c46' },
  clockwork: { name: 'The Brass Republic', eyebrow: 'EVERY REVOLUTION STARTS SOMEWHERE', description: 'An enormous brass gear, copper workshops, chimney stacks, and an elevated aqueduct.', accent: '#e3bc76', ground: '#a59475', base: '#584936', tile: '#e9dab9', sky: '#302d2a' },
  standard: { name: 'Civic Gardens', eyebrow: 'THE ORIGINAL DISTRICT', description: 'Terracotta rooftops, tree-lined avenues, and a clock tower at the heart of it all.', accent: '#e6ab69', ground: '#91a984', base: '#344944', tile: '#e9e4d3', sky: '#172e2b' },
  cyber: { name: 'Neon Circuit', eyebrow: 'AFTER HOURS, ABOVE THE CITY', description: 'A vertical metropolis of luminous towers, elevated links, and a floating data core.', accent: '#6aeddc', ground: '#1d3443', base: '#15232e', tile: '#476176', sky: '#10252d' },
  poker: { name: 'The High Roller', eyebrow: 'A SEAT AT THE BIG TABLE', description: 'Chip-stack skyscrapers, a house of cards, and a golden crown over deep green felt.', accent: '#e4bd72', ground: '#28664e', base: '#57392b', tile: '#f3e8cc', sky: '#18392c' },
  pride: { name: 'Max Gay Ass Pride Board', eyebrow: 'EVERY COLOUR BELONGS', description: 'Walk beneath a sculpted rainbow, past a festival stage and a colourful observation wheel.', accent: '#efa6d1', ground: '#b6c6ac', base: '#806c99', tile: '#f4e7e3', sky: '#342e46' },
  dummy: { name: 'Block Party', eyebrow: 'BUILD SOMETHING UNEXPECTED', description: 'A playful construction world of stacked blocks, a working skyline, and a giant yellow crane.', accent: '#e4cb75', ground: '#8ba4b1', base: '#394b66', tile: '#e7e3db', sky: '#223244' },
};
export function worldTheme(id: string): WorldTheme { return WORLD_THEMES[id] ?? WORLD_THEMES.standard; }
