import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { AccountStore } from '../src/accounts.js';
import { createGame, renameTile, removeCard, addCard, applyTemplate } from '@marxopoly/shared';

test('accounts persist, protect passwords, isolate templates and revoke sessions', async t => {
  const directory = await mkdtemp(path.join(tmpdir(), 'common-ground-accounts-'));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const filename = path.join(directory, 'accounts.json');
  const store = new AccountStore(filename);
  await assert.rejects(store.authenticate('Alice', 'short', true));
  const alice = await store.authenticate('Alice', 'a long password', true);
  await assert.rejects(store.authenticate('alice', 'a long password', true), /taken/);
  await assert.rejects(store.authenticate('Alice', 'wrong password', false), /incorrect/);
  const bob = await store.authenticate('Bob', 'another password', true);
  let state = renameTile(createGame('source', [{ id: 'a', name: 'Alice' }]), 1, 'University Road');
  const removed = state.cards[0]!.id;
  state = removeCard(state, removed);
  state = addCard(state, { id: 'custom', deck: 'fortune', text: 'A gift', effect: { kind: 'cash', amount: 123 } });
  const saved = await store.save(alice.token, 'Campus', state);
  const id = saved.templates[0]!.id;
  state.tileNames[1] = 'Later edit';
  saved.templates[0]!.cards.length = 0;
  await assert.rejects(store.template(bob.token, id), /no longer exists/);
  await assert.rejects(store.delete(bob.token, id), /no longer exists/);
  await assert.rejects(store.save(bob.token, 'Hijack', state, id), /no longer exists/);
  const restarted = new AccountStore(filename);
  const recovered = await restarted.template(alice.token, id);
  assert.equal(recovered.tileNames[1], 'University Road');
  assert.ok(recovered.cards.some(c => c.id === 'custom'));
  assert.ok(!recovered.cards.some(c => c.id === removed));
  const fresh = createGame('new-room', [{ id: 'b', name: 'Bob' }]);
  const applied = applyTemplate(fresh, recovered);
  assert.equal(applied.id, 'new-room');
  assert.equal(applied.players[0]!.id, 'b');
  assert.deepEqual(applied.cards, recovered.cards);
  assert.deepEqual([...applied.fortuneDeck].sort(), recovered.cards.filter(c => c.deck === 'fortune').map(c => c.id).sort());
  assert.deepEqual([...applied.ledgerDeck].sort(), recovered.cards.filter(c => c.deck === 'ledger').map(c => c.id).sort());
  assert.deepEqual(fresh.tileNames, {});
  const updated = await restarted.save(alice.token, 'Campus revised', state, id);
  assert.equal(updated.templates.length, 1);
  assert.equal(updated.templates[0]!.name, 'Campus revised');
  const raw = await readFile(filename, 'utf8');
  assert.ok(!raw.includes('a long password'));
  assert.ok(!raw.includes(alice.token));
  await restarted.delete(alice.token, id);
  assert.deepEqual((await restarted.restore(alice.token)).templates, []);
  await restarted.logout(alice.token);
  await assert.rejects(restarted.restore(alice.token), /sign in again/);
  assert.equal((await restarted.authenticate('ALICE', 'a long password', false)).username, 'Alice');
});

test('concurrent writes survive restart and expired sessions are rejected', async t => {
  const directory = await mkdtemp(path.join(tmpdir(), 'common-ground-accounts-'));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const filename = path.join(directory, 'accounts.json');
  const store = new AccountStore(filename);
  const account = await store.authenticate('Tester', 'a long password', true);
  const state = createGame('test', [{ id: 'a', name: 'Tester' }]);
  await Promise.all([store.save(account.token, 'First', state), store.save(account.token, 'Second', state)]);
  assert.equal((await new AccountStore(filename).restore(account.token)).templates.length, 2);
  const raw = JSON.parse(await readFile(filename, 'utf8'));
  raw[0].sessions[0].expires = 0;
  await writeFile(filename, JSON.stringify(raw));
  await assert.rejects(new AccountStore(filename).restore(account.token), /sign in again/);
});
